name: lifeqa
channels:
  - pytorch
  - defaults
dependencies:
  # The direct and indirect dependencies are pinned for reproducibility purposes.
  # However, some few indirect dependencies as well as all the dependency hashes are not kept so this file can be used
  #   both in Linux and MacOS.
  # TODO: pin indirect dependencies when the project is done and the direct dependencies don't change anymore.

  - pip:
    # --- Pip direct dependencies: ---
    - allennlp==git+https://github.com/allenai/allennlp@f8b10a9
    # apex is quite slow to compile, so we leave it out.
    #- git+https://github.com/NVIDIA/apex@74c06d8 --global-option="--cpp_ext" --global-option="--cuda_ext"
    - conllu==1.2.3  # Incompatible version for allennlp, but needed for the 'analysis'. So just change the version when
    # running the analysis.
    - google-cloud-speech==0.36.3
    - overrides==1.9

#    # --- Pip indirect dependencies: ---
#    - atomicwrites==1.3.0
#    - awscli==1.16.96
#    - boto3==1.9.86
#    - botocore==1.12.86
#    - cachetools==3.1.0
#    - cryptography==2.5
#    - dill==0.2.9
#    - docker==3.7.0
#    - docker-pycreds==0.4.0
#    - editdistance==0.5.2
#    - ftfy==5.5.1
#    - google-api-core==1.7.0
#    - google-auth==1.6.2
#    - googleapis-common-protos==1.5.6
#    - grpcio==1.18.0
#    - jsonnet==0.10.0
#    - jsonpickle==1.1
#    - moto==1.3.4
#    - msgpack==0.5.6
#    - packaging==19.0
#    - parsimonious==0.8.0
#    - pbr==5.1.2
#    - pyasn1-modules==0.2.4
#    - pycryptodome==3.7.3
#    - pytest==4.2.0
#    - pytorch-pretrained-bert==0.4.0
#    - regex==2018.1.10
#    - rsa==3.4.2
#    - spacy==2.0.18
#    - sphinx==1.8.4
#    - tensorboardx==1.2
#    - thinc==6.12.1  # Available in Conda, but that version requires an incompatible version of MKL.

  # --- Conda direct dependencies: ---
  - cudatoolkit=10.0
  - cudnn=7.3.1
  - ffmpeg=4.0
  - h5py=2.9.0
  - nltk=3.4
  - numpy=1.16.2
  - pillow=5.4.1
  - pip=19.0.3
  - python=3.7.2
  - pytorch=1.0.1
  - torchvision=0.2.2
  - tqdm=4.31.1

#  # --- Conda indirect dependencies: ---
#  - alabaster=0.7.12
#  - asn1crypto=0.24.0
#  - attrs=18.2.0
#  - aws-xray-sdk=0.95
#  - Babel=2.6.0
#  - blas=1.0
#  - boto=2.49.0
#  - ca-certificates=2018.12.5
#  - certifi=2018.11.29
#  - cffi=1.11.5
#  - Click=7.0
#  - colorama=0.3.9
#  - cookies=2.2.1
#  - cycler=0.10.0
#  - cymem=2.0.2
#  - cytoolz=0.9.0.1
#  - docutils=0.14
#  - ecdsa=0.13
#  - flaky=3.5.3
#  - Flask=1.0.2
#  - Flask-Cors=3.0.7
#  - freetype=2.9.1
#  - future=0.17.1
#  - gevent=1.3.6
#  - greenlet=0.4.15
#  - hdf5=1.10.2
#  - imagesize=1.1.0
#  - intel-openmp=2019.1
#  - itsdangerous=1.1.0
#  - Jinja2=2.10
#  - jmespath=0.9.3
#  - jpeg=9b
#  - jsondiff=1.1.1
#  - kiwisolver=1.0.1
#  - libedit=3.1.20181209
#  - libffi=3.2.1
#  - libpng=1.6.36
#  - libtiff=4.0.10
#  - MarkupSafe=1.1.0
#  - matplotlib=2.2.3
#  - mkl=2019.1
#  - mkl_fft=1.0.10
#  - mkl_random=1.0.2
#  - mock=2.0.0
#  - more-itertools=5.0.0
#  - msgpack-numpy=0.4.3.2
#  - murmurhash=1.0.1
#  - ncurses=6.1
#  - numpy-base=1.15.4
#  - numpydoc=0.8.0
#  - olefile=0.46
#  - openssl=1.1.1b
#  - plac=0.9.6
#  - pluggy=0.8.1
#  - preshed=2.0.1
#  - protobuf=3.6.1
#  - py=1.7.0
#  - pyaml=18.11.0
#  - pyasn1=0.4.5
#  - pycparser=2.19
#  - Pygments=2.3.1
#  - pyparsing=2.3.1
#  - python-jose=2.0.2
#  - pytz=2017.3
#  - PyYAML=3.13
#  - readline=7.0
#  - responses=0.10.5
#  - s3transfer=0.1.13
#  - scikit-learn=0.20.2
#  - scipy=1.2.0
#  - setuptools=40.6.3
#  - six=1.12.0
#  - snowballstemmer=1.2.1
#  - sphinxcontrib-websupport=1.1.0
#  - sqlite=3.27.2
#  - sqlparse=0.2.4
#  - tk=8.6.8
#  - toolz=0.9.0
#  - ujson=1.35
#  - wcwidth=0.1.7
#  - websocket-client=0.54.0
#  - Werkzeug=0.14.1
#  - wheel=0.32.3
#  - wrapt=1.10.11
#  - xmltodict=0.11.0
#  - xz=5.2.4
#  - zlib=1.2.11
#  - zstd=1.3.7
