name: lifeqa
channels:
  - pytorch
  - defaults
dependencies:
  - pip:
    - git+https://github.com/bryant1410/allennlp@7577857  # See allenai/allennlp #2805, #2835 and 'lqa' branch.
    # Optional. Takes some time to compile but may make the execution faster:
    #- git+https://github.com/NVIDIA/apex@4ff153c --global-option="--cpp_ext" --global-option="--cuda_ext"
    - conllu==1.2.3  # Incompatible version for allennlp, but needed for the 'analysis'. So just change the version when
    # needed.
    - google-cloud-speech==0.36.3
    - jsonlines==1.2.0
    - jsonnet==0.12.1
    - overrides==1.9
    - scipy==1.4.1
    - youtube-dl==2020.03.24
  - cudatoolkit=10.0
  - cudnn=7.3.1
  - ffmpeg=4.0
  - gsl=2.4
  - h5py=2.8.0
  - nltk=3.4.1
  - numpy=1.18.1
  - opencv=3.4.2
  - pandas=0.24.2
  - pillow=5.4.1
  - pip=19.1
  - python=3.7.3
  - pytorch=1.1.0
  - scikit-image=0.16.2
  - scikit-learn=0.20.3
  - tensorboard=1.13.1
  - tensorflow=1.13.1  # For tensorboard
  - torchvision=0.2.2
  - tqdm=4.31.1
